### ISSUE TITLE
leveldown.node error

### ISSUE THREAD

**Issue by MagicLizi** [mistakia/record-app#1]
hello，i checkout your project and want to run on iPhoneX，but i get an error，how can i fix it，i realy need your help

```
leveldown.node: mach-o, but wrong architecture
```

**Comment by MagicLizi** [comment]
FULL ERROR
```
Error: dlopen(/private/var/containers/Bundle/Application/4A335527-4CCA-40C7-B743-F4319181BB41/Record.app/nodejs-project/node_modules/leveldown/build/Release/leveldown.node, 1): no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/4A335527-4CCA-40C7-B743-F4319181BB41/Record.app/nodejs-project/node_modules/leveldown/build/Release/leveldown.node: mach-o, but wrong architecture
	/private/var/containers/Bundle/Application/4A335527-4CCA-40C7-B743-F4319181BB41/Record.app/nodejs-project/node_modules/leveldown/build/Release/leveldown.node: mach-o, but wrong architecture
   at bindings (/private/var/containers/Bundle/Application/4A335527-4CCA-40C7-B743-F4319181BB41/Record.app/nodejs-project/node_modules/bindings/bindings.js:88:9)
   at Anonymous function (/private/var/containers/Bundle/Application/4A335527-4CCA-40C7-B743-F4319181BB41/Record.app/nodejs-project/node_modules/leveldown/leveldown.js:4:7)
   at Module.prototype._compile (module.js:624:5)
   at Module._extensions[.js] (module.js:635:3)
   at Module.prototype.load (module.js:545:3)
   at tryModuleLoad (module.js:508:5)
   at Module._load (module.js:500:3)
   at Module.prototype.require (module.js:568:3)
   at require (internal/module.js:11:7)
   at Anonymous function (/private/var/containers/Bundle/Application/4A335527-4CCA-40C7-B743-F4319181BB41/Record.app/nodejs-project/node_modules/datastore-level/src/index.js:8:1)
```

**Comment by xuruijing** [comment]
checkout new version project,  run in Xcode（simulator） ，
`Usage: codesign -s identity [-fv*] [-o flags] [-r reqs] [-i ident] path ... # sign
       codesign -v [-v*] [-R=<req string>|-R <req file path>] path|[+]pid ... # verify
       codesign -d [options] path ... # display contents
       codesign -h pid ... # display hosting paths
Command /bin/sh failed with exit code 2`
Where the question is

**Comment by mistakia** [comment]
@MagicLizi I made a few changes that should make it more straight forward to build and run on xcode. 

Using the latest version, to run on simulator (or a device) - use the command `npm install` to install packages for the app as well as for the nodejs-mobile script, then you should be able to build on xcode. The only issue you may have is with the [human-to-milliseconds](https://github.com/hacdias/human-to-milliseconds) package. You may have to change the following [line](https://github.com/hacdias/human-to-milliseconds/blob/master/src/index.js#L12) to `'µs': 0.001,` (put quotes around µ).

To run on your device, you'll have to comment this [line](https://github.com/mistakia/record-app/blob/master/ios/record/AppDelegate.m#L22) and uncomment this [line](https://github.com/mistakia/record-app/blob/master/ios/record/AppDelegate.m#L24). Then run `npm run build:ios` before building on xcode.

Ipfs works pretty well on simulator - but it's currently excruciatingly slow on my iPhone 6+. I'd be interested to see how it runs on your X. I think the performance issue might be rooted in the nodejs-mobile package as it sometimes takes 5-6 mins for nodejs-mobile to initialize.
