### ISSUE TITLE
Npm install error

### ISSUE THREAD

**Issue by mistakia** [mistakia/record-app#2]
continuation of an issue opened at mistakia/record-node#1

At first glance it looks like it is unable to download and install [electron](https://github.com/electron/electron).

@xuruijing — Try `npm install` with the latest version and let me know if you have any issues. I've included an updated `package-lock.json` file inside `nodejs-assets/nodejs-project` to assist with installing a version of leveldown that will build for ios.

**Comment by mistakia** [comment]
What version of npm are you using? Make sure it is 5 or newer.

Try again with the latest commit but first clear your npm cache with `npm run clean` or `npm cache clean --force`.

It seems like you are getting an error for an invalid version of lock-me@1.0.4 even though it definitely [exists](https://www.npmjs.com/package/lock-me/v/1.0.4).

**Comment by xuruijing** [comment]
According to your steps after the problem still exists, I use the command NPM I lock - me, even though there are errors in the process, but in the end tip + lock-me@1.0.3, does this suggest that can take to the latest version is now 1.0.3. How do I modify the next step to get the complete dependency package。`npm -v` 5.6.0, `node -v` 8.11.1

**Comment by mistakia** [comment]
Are you able to resolve and download the following [https://registry.npmjs.org/lock-me/-/lock-me-1.0.4.tgz](https://registry.npmjs.org/lock-me/-/lock-me-1.0.4.tgz)?

**Comment by mistakia** [comment]
No - those warnings should not have any affect on running the app.

**Comment by xuruijing** [comment]
When I generate the file `main.jsbundle` in IOS project, I am prompted for a path error.
`error: bundling failed: Error: Unable to resolve module `../node_modules/react-native/src/views/root` from `/Users/xuruijing/Downloads/record-app-master-3/src/index.ios.js`: The module `../node_modules/react-native/src/views/root` could not be found from `/Users/xuruijing/Downloads/record-app-master-3/src/index.ios.js`. Indeed, none of these files exist:

  * `/Users/xuruijing/Downloads/record-app-master-3/node_modules/react-native/src/views/root(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `/Users/xuruijing/Downloads/record-app-master-3/node_modules/react-native/src/views/root/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`

Whether the `import Root from '@views/root'` refers to a path requires additional configuration

**Comment by mistakia** [comment]
the path configuration is set in `.babelrc` using the `babel-plugin-module-resolver`. Perhaps make sure that the babel plugin is installed and that the `.babelrc` file is present at the root directory of the repo.

Are you generating the bundle by running `npm run build:ios`?

**Comment by xuruijing** [comment]
The `.babelrc` file is in the root directory of the repo.
`xuruijingdeMacBook-Pro:record-app-master-3 xuruijing$ ls -a
.			android			main.jsbundle
..			app.json		node_modules
.DS_Store		config			nodejs-assets
.babelrc		electron.js		package-lock.json
.gitattributes		index.desktop.html	package.json
.gitignore		index.web.html		src
Gruntfile.js		ios			yarn.lock`

then I run `npm run build:ios`
`xuruijingdeMacBook-Pro:record-app-master-3 xuruijing$ npm run build:ios

> Record@0.0.1 build:ios /Users/xuruijing/Downloads/record-app-master-3
> react-native bundle --reset-cache --entry-file src/index.ios.js --bundle-output ios/main.jsbundle --platform ios --dev false

Scanning folders for symlinks in /Users/xuruijing/Downloads/record-app-master-3/node_modules (55ms)
Scanning folders for symlinks in /Users/xuruijing/Downloads/record-app-master-3/node_modules (39ms)
Loading dependency graph, done.
warning: the transform cache was reset.
bundle: start
bundle: finish
bundle: Writing bundle output to: ios/main.jsbundle
bundle: Done writing bundle output
Assets destination folder is not set, skipping...`

is right?
iOS project clean and run again, the error remains the same. What am I missing?

**Comment by mistakia** [comment]
In `ios/record/AppDelegate.m` comment this [line](https://github.com/mistakia/record-app/blob/master/ios/record/AppDelegate.m#L22) and uncomment this [line](https://github.com/mistakia/record-app/blob/master/ios/record/AppDelegate.m#L24). This will use the bundled app from the build instead of getting it from the react native metro bundler.

It seems like the metro bundler is running in your situation - so thats not the issue but just to be safe before you do xcode run, start the bundler with `npm run start` - this is the preferred way as it passes in the `--reset-cache` flag. Also, this only matters if [jslocation in AppDelegate.m is set to use the metro bundler](https://github.com/mistakia/record-app/blob/master/ios/record/AppDelegate.m#L22).

There seem to be some [issues](https://github.com/tleunen/babel-plugin-module-resolver/issues/224) reported with using the module-resolver plugin with react native, however, I am currently not able to reproduce it on my end.

**Comment by xuruijing** [comment]
Thank you very much for your guidance. I am now able to run on the simulator. Now I plan to package it into IPA file and run it in my mobile phone. What should I do? Need to regenerate the main.jsbunle file? I changed the bunldeID and signing in XCODE to my own, but I still gave the code Siging Error

`Code Signing Error: No account for team "8PU8BA3SQD". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.
Code Signing Error: No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "8PU8BA3SQD" with a private key was found.
Code Signing Error: Code signing is required for product type 'Unit Test Bundle' in SDK 'iOS 11.2'
Code Signing Error: No account for team "8PU8BA3SQD". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.`

**Comment by xuruijing** [comment]
Now I have solved the above problem, the program can run on apple mobile phone, but now there are two problems need your help: 
1. From the point of view of the log IPFS node launched, but the API and GATEWAY port number is 0, I write their address in the ipfsConfig, the log shows as follows:
`"Addresses": {
    "Swarm": [],
    "API": "/ip4/127.0.0.1/tcp/5002",
    "Gateway": "/ip4/127.0.0.1/tcp/9090"
  },`。 But I can't access this gateway。Does this gateway work properly?
2.Shortly after the program runs, the following error prompts appear regularly
`Error: already piped
   at sink (/private/var/containers/Bundle/Application/18EBD591-352F-46C2-A5A5-150C64D7105F/Record.app/nodejs-project/node_modules/pull-pair/index.js:11:7)
   at consume (/private/var/containers/Bundle/Application/18EBD591-352F-46C2-A5A5-150C64D7105F/Record.app/nodejs-project/node_modules/pull-defer/sink.js:7:17)`

**Comment by xuruijing** [comment]
in `main.js`, use Debug module to log( `const log = debug('main')` ) , after running this code,  in IOS, NSLOG can no longer output information on console. Is there a redirect？How to solve？

**Comment by mistakia** [comment]
By default on iOS, it logs to the debug pane inside Xcode.
