### ISSUE TITLE
Latest version file path error

### ISSUE THREAD

**Issue by xuruijing** [mistakia/record-app#5]
With the latest version, `npm run start:ios`, the following file path error occurs. How to modify it.
The simulator is the same as the iphone.
![2018-06-11 6 20 46](https://user-images.githubusercontent.com/15903078/41226619-9722066c-6da4-11e8-9cb2-4a78ad772efd.png)

**Comment by mistakia** [comment]
I think I know whats going on. Before you run `npm run start:ios`, in another terminal run `npm run start`. Let me know if that clears it up on the simulator.

Are you also running into this on the device?

**Comment by xuruijing** [comment]
If run `npm run start:ios` directly, there will be other errors.

`In file included from /Users/xuruijing/Downloads/record-app-master-0612/node_modules/react-native/Libraries/Geolocation/RCTLocationObserver.m:10:
/Users/xuruijing/Downloads/record-app-master-0612/node_modules/react-native/Libraries/Geolocation/RCTLocationObserver.h:10:9: fatal error: 'React/RCTEventEmitter.h' file not found
#import <React/RCTEventEmitter.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~`

`Installing build/Build/Products/Debug-iphonesimulator/Record.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Record.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist`

I looked at Xcode's scheme, and I felt something was wrong here. In xcode->edit scheme->build, react configuration item is missing, Is it this problem? Otherwise there will be errors in the simulator and device compilation
